[".vim/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"
[".tmux/plugins/tpm"]
  type = "archive"
  url = "https://github.com/tmux-plugins/tpm/archive/master.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
{{ if eq .chezmoi.os "linux" -}}
[".wsl"]
  type = "archive"
  url = "https://github.com/rupor-github/win-gpg-agent/releases/download/v1.5.0/win-gpg-agent.zip"
  exact = true
{{- end -}}
